export const equipmentOptions = [
  "ABS",
  "Control de estabilidad",
  "Control de tracción",
  "Airbags frontales",
  "Airbags laterales",
  "Airbags de cortina",
  "Cámara de retroceso",
  "Sensores delanteros",
  "Sensores traseros",
  "Pantalla multimedia",
  "Apple CarPlay",
  "Android Auto",
  "Bluetooth",
  "GPS",
  "Climatizador",
  "Tapizado de cuero",
  "Techo panorámico",
  "Llantas de aleación",
  "Faros LED",
  "Control crucero",
];
export const vehicles = [

  {
    
  id: 1,
  slug: "jeep-renegade-longitude-2023",
  marca: "Jeep",
  modelo: "Renegade Longitude",
  año: 2023,
  kilometros: "18.000 km",
  combustible: "Nafta",
  transmision: "Automática",
motor: "1.8 E.torQ Flex",
potencia: "130 CV",
traccion: "4x2",
colorExterior: "Blanco",
precio: "$36.900.000",
  descripcion:
    "Jeep Renegade Longitude 2023 en excelente estado general. Único dueño, todos los services realizados en tiempo y forma. Listo para transferir. Recibimos vehículos en parte de pago y ofrecemos financiación.",
  imagenes: [
    "/images/renegade1.jpeg",
    "/images/renegade2.jpeg",
    "/images/renegade3.jpeg",
  ],
  destacado: true,
},
  {
    id: 2,
    slug: "nissan-frontier-xe-2022",
    marca: "Nissan",
    modelo: "Frontier XE",
    año: 2022,
    kilometros: "42.000 km",
    combustible: "Diésel",
    transmision: "Manual",
    precio: "$45.500.000",
   imagenes: [
  "/images/amarok1.jpeg",
],
    destacado: true,
  },
  {
    id: 3,
    slug: "volkswagen-amarok-v6-2023",
    marca: "Volkswagen",
    modelo: "Amarok V6",
    año: 2023,
    kilometros: "24.000 km",
    combustible: "Diésel",
    transmision: "Automática",
    precio: "$58.900.000",
   imagenes: [
  "/images/amarok1.jpeg",
],
    destacado: true,
  },
  {
    id: 4,
    slug: "toyota-corolla-xei-2023",
    marca: "Toyota",
    modelo: "Corolla XEI",
    año: 2023,
    kilometros: "27.000 km",
    combustible: "Nafta",
    transmision: "Automática",
    precio: "$38.700.000",
   imagenes: [
  "/images/amarok1.jpeg",
],
    destacado: true,
  },
  {
    id: 5,
    slug: "toyota-yaris-xls-2024",
    marca: "Toyota",
    modelo: "Yaris XLS",
    año: 2024,
    kilometros: "9.000 km",
    combustible: "Nafta",
    transmision: "CVT",
    precio: "$29.900.000",
  imagenes: [
  "/images/amarok1.jpeg",
],
    destacado: true,
  },
  {
    id: 6,
    slug: "byd-dolphin-2025",
    marca: "BYD",
    modelo: "Dolphin",
    año: 2025,
    kilometros: "0 km",
    combustible: "Eléctrico",
    transmision: "Automática",
    precio: "Consultar",
   imagenes: [
  "/images/amarok1.jpeg",
],
    destacado: true,
  },
];