-- ===========================================================
-- MotoCars ERP
-- Detalle estructurado de pagos para operaciones de compra
-- ===========================================================

create table if not exists public.pagos_compra (
  id bigint generated by default as identity primary key,

  operacion_id bigint not null
    references public.operaciones(id)
    on delete cascade,

  medio_pago text not null
    check (
      medio_pago in (
        'efectivo',
        'transferencia',
        'cheque',
        'otro'
      )
    ),

  importe numeric(14,2) not null
    check (importe > 0),

  banco text,
  titular text,
  cuil_cuit text,
  tipo_cuenta text,
  numero_cuenta text,
  alias text,
  cbu_cvu text,

  detalle text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pagos_compra_operacion_id_idx
  on public.pagos_compra(operacion_id);